inherit_from:
  - https://raw.githubusercontent.com/thoughtbot/guides/master/style/ruby/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'gemfiles/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  CountComments: true
  Max: 25
  ExcludedMethods: []
  Exclude:
    - "spec/**/*"
    - '*.gemspec'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatStringToken:
  Enabled: false

Style/MethodMissing:
  Exclude:
    - 'lib/factory_bot/decorator.rb'
    - 'lib/factory_bot/decorator/invocation_tracker.rb'
    - 'lib/factory_bot/definition_proxy.rb'
    - 'lib/factory_bot/evaluator.rb'

# TODO: gradually bring this down to 80 as we fix files
# Let's not open a big PR to fix all of these at once - 
# we can fix gradually if we happen to be editing a file that has a violation
Metrics/LineLength:
  Max: 142
