name: Build
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - truffleruby
          - "4.0"
          - "3.4"
          - "3.3"
          - "3.2"
        rails:
          - "7.2"
          - "8.0"
          - main
        exclude:
          # Rails >= 8.1 requires Ruby 3.3
          - { ruby: "3.2", rails: "main" }
          # 2025-10-23 There's an incompatibility between truffleruby and rails edge Git ref
          # results in a "NoMethodError: undefined method `[]' for class Fiber" error whilst running specs
          - { ruby: truffleruby, rails: "main" }

    runs-on: 'ubuntu-latest'

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rake all_specs

  standard:
    name: Run standard
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rake standard
